version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore cached dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install new dependencies
          command: yarn install

      - save_cache:
          name: Cache new dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run linting
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test
